import type { Post, Comment, AnonIdentity } from '../types';

export const MOCK_IDENTITIES: AnonIdentity[] = [
  { id: 'id-1', displayName: 'Silent Heron',   createdAt: '2025-01-01T00:00:00Z' },
  { id: 'id-2', displayName: 'Coastal Cedar',  createdAt: '2025-01-02T00:00:00Z' },
];

export const MOCK_POSTS: Post[] = [
  {
    id: 'post-1',
    channel: 'general',
    anonIdentityId: 'id-1',
    anonDisplayName: 'Silent Heron',
    textBody: 'Anyone else think the library is freezing cold today? It has to be 60 degrees in here.',
    upvoteCount: 24,
    commentCount: 3,
    shareCount: 1,
    createdAt: '2025-03-11T10:30:00Z',
    upvotedByMe: false,
  },
  {
    id: 'post-2',
    channel: 'general',
    anonIdentityId: 'id-2',
    anonDisplayName: 'Coastal Cedar',
    textBody: 'Free pizza at the student center at noon. Be there.',
    upvoteCount: 61,
    commentCount: 8,
    shareCount: 14,
    createdAt: '2025-03-11T09:00:00Z',
    upvotedByMe: true,
  },
  {
    id: 'post-3',
    channel: 'dating',
    anonIdentityId: 'id-1',
    anonDisplayName: 'Silent Heron',
    textBody: 'Saw someone reading Camus outside Randolph Hall. If that was you, hi.',
    upvoteCount: 88,
    commentCount: 12,
    shareCount: 3,
    createdAt: '2025-03-11T08:15:00Z',
    upvotedByMe: false,
  },
  {
    id: 'post-4',
    channel: 'dating',
    anonIdentityId: 'id-2',
    anonDisplayName: 'Coastal Cedar',
    textBody: 'Looking for my study partner from the intro econ lecture. We never exchanged numbers.',
    upvoteCount: 47,
    commentCount: 5,
    shareCount: 2,
    createdAt: '2025-03-09T16:30:00Z',
    upvotedByMe: false,
  },
  {
    id: 'post-5',
    channel: 'lore',
    anonIdentityId: 'id-2',
    anonDisplayName: 'Coastal Cedar',
    textBody: 'There is supposedly an underground tunnel system connecting the old buildings. Has anyone actually found the entrance?',
    upvoteCount: 142,
    commentCount: 31,
    shareCount: 22,
    createdAt: '2025-03-10T21:00:00Z',
    upvotedByMe: false,
  },
  {
    id: 'post-6',
    channel: 'lore',
    anonIdentityId: 'id-1',
    anonDisplayName: 'Silent Heron',
    textBody: 'The squirrels on the Cistern are organized. I have watched them hold what can only be described as a meeting.',
    upvoteCount: 209,
    commentCount: 44,
    shareCount: 38,
    createdAt: '2025-03-10T14:00:00Z',
    upvotedByMe: false,
  },
  {
    id: 'post-7',
    channel: 'events',
    anonIdentityId: 'id-1',
    anonDisplayName: 'Silent Heron',
    textBody: 'Spring art show in the Simons Center Gallery tonight at 7pm. Open to all students, free entry.',
    upvoteCount: 53,
    commentCount: 7,
    shareCount: 19,
    createdAt: '2025-03-11T06:00:00Z',
    upvotedByMe: false,
  },
  {
    id: 'post-8',
    channel: 'events',
    anonIdentityId: 'id-2',
    anonDisplayName: 'Coastal Cedar',
    textBody: 'Club tennis tryouts are Saturday at 10am on the back courts. No experience required, just show up.',
    upvoteCount: 31,
    commentCount: 4,
    shareCount: 8,
    createdAt: '2025-03-10T18:00:00Z',
    upvotedByMe: false,
  },
];

export const MOCK_COMMENTS: Comment[] = [
  {
    id: 'c-1',
    postId: 'post-1',
    anonIdentityId: 'id-2',
    anonDisplayName: 'Coastal Cedar',
    text: 'Bring a blanket honestly.',
    createdAt: '2025-03-11T10:45:00Z',
  },
  {
    id: 'c-2',
    postId: 'post-1',
    anonIdentityId: 'id-1',
    anonDisplayName: 'Silent Heron',
    text: 'I heard they keep it cold so people do not fall asleep.',
    createdAt: '2025-03-11T11:00:00Z',
  },
  {
    id: 'c-3',
    postId: 'post-5',
    anonIdentityId: 'id-1',
    anonDisplayName: 'Silent Heron',
    text: 'The entrance is supposedly behind a bookshelf in the basement of Towell Library.',
    createdAt: '2025-03-10T21:30:00Z',
  },
];
